---
- name: Configure Alteon SSL Repository and SSL Policy
  hosts: localhost
  gather_facts: false

  tasks:

    #################################################################
    # Generate SSL Key
    #################################################################

    - name: Generate SSL Key

      radware.radware_modules.alteon_config_alteon_cli_command:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443
          ssh_port: 22
          timeout: 5

        state: present

        parameters:
          alteon_cli_command: >-
            /cfg/slb/ssl/sslid/{{ certificate_id }}/key/gen
            2048

    #################################################################
    # Apply Configuration After SSL Key
    #################################################################

    - name: Apply SSL Key Configuration

      radware.radware_modules.alteon_mng_config:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443

        command: apply

    #################################################################
    # Save Configuration After SSL Key
    #################################################################

    - name: Save SSL Key Configuration

      radware.radware_modules.alteon_mng_config:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443

        command: save

    #################################################################
    # Generate CSR
    #################################################################

    - name: Generate CSR

      radware.radware_modules.alteon_config_alteon_cli_command:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443
          ssh_port: 22
          timeout: 5

        state: present

        parameters:
          alteon_cli_command: >-
            /cfg/slb/ssl/sslid/{{ certificate_id }}/csr/gen
            "{{ common_name }}"

    #################################################################
    # Apply CSR Configuration
    #################################################################

    - name: Apply CSR Configuration

      radware.radware_modules.alteon_mng_config:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443

        command: apply

    #################################################################
    # Save CSR Configuration
    #################################################################

    - name: Save CSR Configuration

      radware.radware_modules.alteon_mng_config:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443

        command: save

    #################################################################
    # Generate Self Signed Server Certificate
    #################################################################

    - name: Generate Server Certificate

      radware.radware_modules.alteon_config_alteon_cli_command:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443
          ssh_port: 22
          timeout: 5

        state: present

        parameters:
          alteon_cli_command: >-
            /cfg/slb/ssl/sslid/{{ certificate_id }}/cert/gen
            "{{ common_name }}"

    #################################################################
    # Apply Server Certificate
    #################################################################

    - name: Apply Server Certificate Configuration

      radware.radware_modules.alteon_mng_config:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443

        command: apply

    #################################################################
    # Save Server Certificate
    #################################################################

    - name: Save Server Certificate Configuration

      radware.radware_modules.alteon_mng_config:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443

        command: save

    #################################################################
    # Create SSL Policy
    #################################################################

    - name: Create SSL Policy

      radware.radware_modules.alteon_config_ssl_policy:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443
          ssh_port: 22
          timeout: 5

        state: present

        parameters:
          index: "{{ ssl_policy_id }}"
          be_ssl_encryption: enabled
          secure_renegotiation: 5
          fe_cipher_suite: main
          be_hw_offload_rsa: disabled
          pass_ssl_info_add_front_end_https_header: enabled
          fe_intermediate_ca_chain_type: none

    #################################################################
    # Apply SSL Policy
    #################################################################

    - name: Apply SSL Policy

      radware.radware_modules.alteon_mng_config:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443

        command: apply

    #################################################################
    # Save SSL Policy
    #################################################################

    - name: Save SSL Policy

      radware.radware_modules.alteon_mng_config:

        provider:
          server: "{{ management_ip }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: false
          https_port: 443

